spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://188.127.169.9:3306/empleados?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: curso
    password: Cursocurso1;
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  data:
    rest:
      base-path: /api